### ISSUE TITLE
Can expect-expect have an option to ignore steps not having expect?

### ISSUE THREAD

**Issue by AndyGleed** [playwright-community/eslint-plugin-playwright#151] opened 2023-06-29 08:42 UTC
When writing tests, I use a lot of async steps to keep traces/html report nice and neat, and quite often, these steps will not contain an expect statement until I get to the end of the test.

Currently I need to turn expect-expect off but would like it on.  I can't do this unless there would be an option to ignore no expect in steps, but error if there is no expect at all inside the test.

Does that make sense?

**Comment by AndyGleed** [comment] 2023-06-29 08:48
Correct usages of above request:

`
test(`Good 1`, async ({ page}) => {
    await test.step(`Step 1`, async () => {
       await page.getByRole('button', { name: 'foo' }).click();
    });

    await test.step(`Step 2`, async () => {
       await page.getByRole('button', { name: 'bar' }).click();
       await expect(page.locator('.title')).toHaveText('baz');
    });
});

test(`Good 2`, async ({ page}) => {
    await test.step(`Step 1`, async () => {
       await page.getByRole('button', { name: 'foo' }).click();
    });

    await test.step(`Step 2`, async () => {
       await page.getByRole('button', { name: 'bar' }).click();       
    });

    await expect(page.locator('.title')).toHaveText('baz');
});
`

Incorrect usage of above:

`
test(`Bad 1`, async ({ page}) => {
    await test.step(`Step 1`, async () => {
       await page.getByRole('button', { name: 'foo' }).click();
    });

    await test.step(`Step 2`, async () => {
       await page.getByRole('button', { name: 'bar' }).click();
    });
});

test(`Bad 2`, async ({ page}) => {
    await page.getByRole('button', { name: 'foo' }).click();
    await page.getByRole('button', { name: 'bar' }).click();       
});

**Comment by mskelton** [comment] 2023-06-30 03:23
Duplicate of #149 which was released in [v0.15.2](https://github.com/playwright-community/eslint-plugin-playwright/releases/tag/v0.15.2)

**Closed by mskelton** 2023-06-30 03:23 UTC
