### ISSUE TITLE
Wait For methods inside test.step trigger @typescript-eslint/no-unsafe-return

### ISSUE THREAD

**Issue by genopulido-tsn** [playwright-community/eslint-plugin-playwright#109] opened 2022-10-24 02:16 UTC
Example: 

```
test.step('important waiting step that less-technical people (who view our reporter) need to know is important', async () => page.locator('#slow-loading-page-thing').waitFor())
``` 

The above requires me to append `as Promise<void>` to keep the linter from triggering, which I'd rather not do because it's type casting... Either that or I'd have to put an ignore line above every single test step (`// eslint-disable-next-line @typescript-eslint/no-unsafe-return`).

Is this expected behavior?

**Comment by mskelton** [comment] 2022-10-24 02:18
Could you share a screenshot of the error message?

**Comment by genopulido-tsn** [comment] 2022-10-24 02:21
Sure, here's what it looks like with the absolute minimum:
![image](https://user-images.githubusercontent.com/106363604/197436098-8b453d08-b4e1-455d-866c-1836a2f92ed5.png)

**Comment by mskelton** [comment] 2022-10-24 02:33
What Playwright version are you using?  I'm not able to reproduce.

![image](https://user-images.githubusercontent.com/25914066/197437361-5145c96c-4b0a-438c-8730-684b2d615246.png)

**Comment by genopulido-tsn** [comment] 2022-10-24 02:41
We currently have playwright 1.27.1, eslint-plugin-playwright 0.11.2, and typescript-eslint 5.39.0. Seems xojs doesn't update typescript-eslint as quickly. Let me check if it happens with a manual update of typescript-eslint

**Comment by genopulido-tsn** [comment] 2022-10-24 03:04
I installed playwright, the playwright eslint plugin, tslint, and xo on a fresh npm project and have discovered that it happens only with xo's linter. Mea culpa. Seems we'll have to wait for xo's eslint to be updated, which I hope will be soon because I've already added a lot of eslint-disable lines to our tests.

**Comment by mskelton** [comment] 2022-10-24 04:24
Yep, I'll close this

**Closed by mskelton** 2022-10-24 04:24 UTC
