### ISSUE TITLE
[BUG] Issues with valid-title and valid-describe-callback

### ISSUE THREAD

**Issue by vladkrasn** [playwright-community/eslint-plugin-playwright#257] opened 2024-02-27 07:49 UTC
1. They trigger on test.describe.configure
<img width="691" alt="image" src="https://github.com/playwright-community/eslint-plugin-playwright/assets/28753668/9e3f825c-e05c-4c4e-965f-275874c54bea">

2. On test.skip's condition
![image](https://github.com/playwright-community/eslint-plugin-playwright/assets/28753668/31d11b54-b146-469c-be49-013a6e08c745)

**Comment by mskelton** [comment] 2024-02-27 12:40
Duplicate of #258

**Closed by mskelton** 2024-02-27 12:40 UTC
